version: '3.9'

services:
  db:
    image: postgres:16
    container_name: taskmanager_db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build: .
    container_name: taskmanager_web
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      DJANGO_SETTINGS_MODULE: core.settings
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: taskmanager
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:
